project:
  type: website
  output-dir: docs

website:
  title: "NKstats"
  navbar:
    right:
      - text: "About"
        href: about.html
      - text: "Research & Presentation"
        menu:
          - text: "Research"
            href: research.html
          - text: "Presentation"
            href: conference.html
      - text: "Blog"
        href: blog.html
      - icon: envelope
        href: about.html
      - icon: github
        href: https://github.com/NKstats
      - icon: linkedin
        href: https://www.linkedin.com/in/se3008
    left:
      - icon: "moon"
        href: "javascript:toggleDarkMode();"

format:
  html:
    katex: true
    theme: cosmo
    include-before: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <style>
        body {
          font-family: 'Arial', sans-serif;
          background-color: white;
          color: black;
          transition: background-color 0s, color 0s;
        }
        .navbar {
          background-color: #87CEEB;
          color: black;
          transition: background-color 0s, color 0s;
          border-bottom: 1px solid white;
        }
        .navbar .navbar-brand, .navbar .nav-link, .navbar a {
          font-size: 18px;
          color: inherit;
          transition: color 0s;
        }
        .navbar .navbar-brand {
          font-size: 19pt;
        }
        body.dark-mode, .navbar.dark-mode {
          background-color: #343a40;
          color: #ffffff;
        }
        .navbar.dark-mode .navbar-brand, .navbar.dark-mode .nav-link, .navbar.dark-mode a {
          color: #ffffff;
        }
        .navbar.dark-mode {
          background-color: #343a40;
        }
        .navbar .nav-link[aria-expanded="true"], .navbar .dropdown-menu a {
          color: black;
          background-color: white;
        }
        .navbar.dark-mode .nav-link[aria-expanded="true"], .navbar.dark-mode .dropdown-menu a {
          color: white;
          background-color: #343a40;
        }
        .back-to-top {
          position: fixed;
          bottom: 20px;
          left: 50%;
          transform: translateX(-50%);
          display: none;
          background-color: white;
          color: black;
          border: 1px solid #343a40;
          border-radius: 2px;
          padding: 8px 18px;
          cursor: pointer;
          font-size: 14px;
          z-index: 1000;
        }
        .back-to-top:hover {
          background-color: #f1f1f1;
        }
        body.dark-mode .back-to-top {
          background-color: #343a40;
          color: white;
          border: 0.5px solid white;
        }
        body.dark-mode .back-to-top:hover {
          background-color: #343a40;
        }
      </style>
    include-after: |
      <script>
        function toggleDarkMode() {
          var body = document.body;
          body.classList.toggle('dark-mode');
          var navbar = document.querySelector('.navbar');
          navbar.classList.toggle('dark-mode');
          var icon = document.querySelector('.fa-moon');
          if (icon) {
            icon.classList.toggle('fa-sun');
            icon.classList.toggle('fa-moon');
          }
          localStorage.setItem('theme', body.classList.contains('dark-mode') ? 'dark' : 'light');
        }

        function applyThemePreference() {
          if (localStorage.getItem('theme') === 'dark') {
            document.body.classList.add('dark-mode');
            document.querySelector('.navbar').classList.add('dark-mode');
            var icon = document.querySelector('.fa-moon');
            if (icon) {
              icon.classList.add('fa-sun');
              icon.classList.remove('fa-moon');
            }
          }
        }

        document.addEventListener('DOMContentLoaded', function() {
          applyThemePreference();
          var button = document.createElement('button');
          button.innerHTML = '&#8679; Back to Top';
          button.className = 'back-to-top';
          document.body.appendChild(button);
          button.onclick = function() {
            document.body.scrollTop = 0; // For Safari
            document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE, and Opera
          };
          window.onscroll = function() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
              button.style.display = "block";
            } else {
              button.style.display = "none";
            }
          };
        });
      </script>