project:
  type: website
  output-dir: docs

website:
  title: "NKstats"
  navbar:
    right:
      - text: "About"
        href: about.html
      - text: "Research"
        menu:
          - text: "Publication"
            href: research.html
          - text: "Conference Presentation"
            href: conference.html
      - text: "Blog"
        href: blog.html
      - icon: envelope
        href: mailto:eshunsolomon5@gmail.com
      - icon: github
        href: https://github.com/NKstats
      - icon: linkedin
        href: https://www.linkedin.com/in/se3008
    left:
      - icon: "moon"
        href: "javascript:toggleDarkMode();"

format:
  html:
    katex: true
    theme: cosmo
    include-before: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <style>
        body {
          font-family: 'Arial', sans-serif;
          background-color: white;
          color: black;
          transition: background-color 0s, color 0s;
        }
        .navbar {
          background-color: #87CEEB;
          color: black;
          transition: background-color 0s, color 0s;
        }
        .navbar .navbar-brand, .navbar .nav-link, .navbar a {
          /*font-weight: bold;*/
          font-size: 18px;
          color: inherit;
          transition: color 0s;
        }
        .navbar .navbar-brand {
          font-size: 19pt;
        }
        body.dark-mode, .navbar.dark-mode {
          background-color: #343a40;
          color: #ffffff;
          border-bottom: 2px solid #606060;
        }
        .navbar.dark-mode .navbar-brand, .navbar.dark-mode .nav-link, .navbar.dark-mode a {
          color: #ffffff;
        }
        .navbar.dark-mode {
          background-color: #343a40;
        }
        .navbar .nav-link[aria-expanded="true"], .navbar .dropdown-menu a {
          color: black;
          background-color: white;
        }
        .navbar.dark-mode .nav-link[aria-expanded="true"], .navbar.dark-mode .dropdown-menu a {
          color: white;
          background-color: #343a40;
        }
      </style>
    include-after: |
      <script>
        function toggleDarkMode() {
          var body = document.body;
          body.classList.toggle('dark-mode');
          var navbar = document.querySelector('.navbar');
          navbar.classList.toggle('dark-mode');
          var icon = document.querySelector('.fa-moon');
          if (icon) {
            icon.classList.toggle('fa-sun');
            icon.classList.toggle('fa-moon');
          }
          if (body.classList.contains('dark-mode')) {
            localStorage.setItem('theme', 'dark');
          } else {
            localStorage.setItem('theme', 'light');
          }
        }
        function applyThemePreference() {
          if (localStorage.getItem('theme') === 'dark') {
            document.body.classList.add('dark-mode');
            document.querySelector('.navbar').classList.add('dark-mode');
            var icon = document.querySelector('.fa-moon');
            if (icon) {
              icon.classList.add('fa-sun');
              icon.classList.remove('fa-moon');
            }
          }
        }
        document.addEventListener('DOMContentLoaded', applyThemePreference);
      </script>

