project:
  type: website
  output-dir: docs

website:
  title: "NKstats"
  navbar:
    right:
      - text: "About"
        href: about.html
      - text: "Research"
        menu:
          - text: "Publication"
            href: research.html
          - text: "Conference Presentation"
            href: conference.html
      - text: "Blog"
        href: blog.html
      - icon: envelope
        href: mailto:eshunsolomon5@gmail.com
      - icon: github
        href: https://github.com/NKstats 
      - icon: linkedin
        href: https://www.linkedin.com/in/se3008

format:
  html:
    katex: true
    theme: cosmo
    include-before: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <style>
        body {
          font-family: 'Arial', sans-serif;
          background-color: white
        }
        .navbar {
          background-color: #87CEEB;
        }
        .navbar .navbar-brand {
          font-weight: bold;
          font-size: 24px;
        }
        .navbar .nav-link {
          font-size: 18px;
        }
      </style>
    /*include-after: |
      <footer>
        <div class="text-center p-3" style="background-color: #f8f9fa;">
          © 2024 Solomon Eshun | All Rights Reserved
        </div>
      </footer>*/
