project:
  type: website
  output-dir: docs

website:
  title: "NKstats"
  navbar:
    right:
      - icon: envelope
        href: mailto:eshunsolomon5@gmail.com
      - icon: github
        href: https://github.com/NKstats 
      - icon: linkedin
        href: https://www.linkedin.com/in/se3008

    left:
      - text: "About"
        href: about.html
      - text: "Research"
        menu:
          - text: "Publication"
            href: research.html
          - text: "Conference Presentation"
            href: conference.html

format:
  html:
    katex: true
    theme: cosmo
    include-before: |
      <style>
        body {
          font-family: 'Arial', sans-serif; /* Sets the font for the entire website */
          background-color: white /* #d9d9d9; /* Soft Beige background for the entire website */
        }
        .navbar {
          background-color: #87CEEB; /* Sky Blue */
        }
        .navbar .navbar-brand {
          font-weight: bold;
          font-size: 24px; /* Larger font size for the navbar brand/title */
        }
        .navbar .nav-link {
          font-size: 18px; /* Increase font size for all navigation links */
        }
      </style>
