project:
  type: website
  output-dir: docs

website:
  title: "Solomon Eshun"
  page-navigation: true
  navbar:
    right:
      - text: "Home"
        href: home.html
      - text: "Research & Presentation"
        menu:
          - text: "Research Work"
            href: research.html
          - text: "Presentation"
            href: conference.html
      - text: "Blog"
        href: blog.html
      - icon: envelope
        href: contact.html
      - icon: github
        href: https://github.com/NKstats
      - icon: linkedin
        href: https://www.linkedin.com/in/se3008
    left:
      - icon: "javascript:toggleDarkMode();"

format:
  html:
    katex: true
    theme: cosmo
    include-before: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <link rel="stylesheet" href="/assets/css/styles.css">
    include-after: |
      <script src="/assets/js/scripts.js"></script>
