---
title: " "
format: html
jupyter: python3
---

<style>
body {
    font-size: 15px;
}
form {
    max-width: 600px;
    margin: auto;
    margin-left: 0;
}
label {
    display: block;
    font-size: 15px;
}
input[type="text"], input[type="email"], textarea {
    width: 100%;
    padding: 15px;
    font-size: 15px;
    margin-top: 10px;
    border: 0.5px solid #ccc;
    border-radius: 10px;
}
button {
    display: block;
    width: auto;
    background-color: #87CEEB;
    color: white;
    border: none;
    cursor: pointer;
    border-radius: 10px;
}
button.send-button {
    font-size: 18px;
    padding: 2px 20px;
    background-color: transparent;
    color: #87CEEB;
    border: 3px solid #87CEEB;
}
button.send-button:hover {
    background-color: #87CEEB;
    color: white;
}
</style>

<div style="height: 20px;"></div>

<div style="font-size: 30px;">Contact</div>

<form action="https://formspree.io/f/xeqybeql" method="POST" id="contactForm">
  <input type="text" id="name" name="name" placeholder="Name" required>
  
  <input type="email" id="email" name="email" placeholder="Email" required>
  
  <textarea id="message" name="message" rows="10" placeholder="Message" required></textarea>
  
  <div style="height: 10px;"></div>
  
  <button type="submit" class="send-button">Send</button>
</form>

<script>
document.addEventListener("DOMContentLoaded", function() {
    var form = document.getElementById('contactForm');
    form.addEventListener('submit', function(event) {
        event.preventDefault(); // Prevent the default form submission
        fetch(form.action, {
            method: 'POST',
            body: new FormData(form),
            headers: {
                'Accept': 'application/json'
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.ok) {
                form.reset(); // Reset the form to clear fields
                alert('Email sent successfully!');
            } else {
                alert('There was an issue with sending the email.');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Error sending message.');
        });
    });
});
</script>
